sonar.projectKey=tozalash-servis
sonar.projectName=Tozalash Servis API
sonar.projectVersion=2.0.0
sonar.sources=app,tests
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/venv/**,**/__pycache__/**,**/migrations/**,**/tests/**
